#!/bin/bash

host=dls013

srcdir=/home/aubert/dev/src-reps/java-balivernes/InfraProfiler/src/
destdir=/home/smd/aubert/public/infrasound/profile-test-env

confdir=/home/aubert/dev/src-reps/java-balivernes/InfraProfiler/conf
confdestdir=$destdir/conf

scriptdir=/home/aubert/dev/src-reps/java-balivernes/InfraProfiler/scripts
scriptdestdir=$destdir/scripts

echo "copy all python files within $srcdir to $host:$destdir"

scp $srcdir/*.py aubert@$host:$destdir
scp $confdir/*.config aubert@$host:$confdestdir
scp $scriptdir/* aubert@$host:$scriptdestdir

echo "copy done"
